# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='alias',
            new_name='username',
        ),
    ]
