# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20180104_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='exam.Users'),
        ),
    ]
