# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20180105_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
