# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20180105_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='wished_for',
        ),
        migrations.AddField(
            model_name='items',
            name='wished_at',
            field=models.ManyToManyField(related_name='wished_items', to='exam.Users'),
        ),
        migrations.AlterField(
            model_name='items',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_uploaded', to='exam.Users'),
        ),
    ]
